events {}

http {
    upstream notification_app {
        server host.docker.internal:3000;
        server host.docker.internal:3001;
        server host.docker.internal:3002;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://notification_app;
        }
    }
}